### ISSUE TITLE
ContextValue of undefined

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#648] opened 2020-03-31 09:54 UTC
![Capture](https://user-images.githubusercontent.com/45042840/78013063-38702500-7346-11ea-9eef-bcf333a15726.PNG)

Steps I did:
1. Create a new member
2. Paste the JCL from clipboard
3. Save it
4. Error appears
5. After this, my profiles are now Invalid and my credentials are replaced by "managed by Zowe Explorer". I need to refresh my workspace

Note: I am using the code from master branch and I have SCS installed

**Comment by stepanzharychevbroadcom** [comment] 2020-04-07 07:00
@jellypuno I tried to reproduce this bug, but no luck. As well as I have no ideas why it might happen. May I ask you to try the same flow out without this additional extension?

**Comment by jellypuno** [comment] 2020-04-07 08:12
@stepanzharychevbroadcom Do you have secure credential store installed?

**Comment by stepanzharychevbroadcom** [comment] 2020-04-07 08:16
@jellypuno I tried it without extensions on clear master. Could you share the link with me and may be some guideline?

**Comment by jellypuno** [comment] 2020-04-07 10:39
I installed this plugin: https://github.com/zowe/zowe-cli-scs-plugin

**Comment by stepanzharychevbroadcom** [comment] 2020-04-07 13:12
I verified saving of _.jcl_ file and submitting it as well. Everything went fine with installed  SCS plugin. To be sure I also removed all of the profiles I had and added everything from scratch. Still no luck.

Used dataset:
![Screenshot 2020-04-07 at 14 33 55](https://user-images.githubusercontent.com/60000150/78673237-24966700-78e2-11ea-897f-d836aca2a1d3.png)

Could someone else try the same flow and confirm it works? @Alexandru-Dumitru @katelynienaber @Colin-Stone @zFernand0

**Comment by jellypuno** [comment] 2020-04-07 14:02
This is the exacts steps that I've done.
1. I opened a JCL in **Profile # 1**. 
2. I Copied the contents of the JCL
3. I opened a dataset in **Profile # 2**
4. I right-clicked then select Create New Member
5. I entered the Member name
6. The editor opens and I pasted the contents that I copied in Step#2
7. I Saved it via Ctrl + S
8. Error Appears.

![contextValueError](https://user-images.githubusercontent.com/45042840/78678255-fec09080-78e8-11ea-8d86-bf42fbf96203.gif)

**Comment by stepanzharychevbroadcom** [comment] 2020-04-07 14:11
@jellypuno I did the same for the attached dataset and there's no error for me. Could you share full error log from the Debug Console, please?

**Comment by katelynienaber** [comment] 2020-04-08 08:34
I get the error, but my profiles are okay still afterwards...

**Comment by stepanzharychevbroadcom** [comment] 2020-04-08 09:27
I still wasn't able to reproduce the following issue myself, even with SCS and using CLI to create profile. It works as it should. Though @katelynienaber was able to reproduce, but she didn't observe profile corruption. @zdmullen I would suggest to put this issue on hold before Katelyn or Jelly can deal with it.

**Comment by jellypuno** [comment] 2020-04-08 10:04
@stepanzharychevbroadcom What do you mean by Katelyn or Jelly can deal with it?

**Comment by katelynienaber** [comment] 2020-04-08 10:05
> @stepanzharychevbroadcom What do you mean by Katelyn or Jelly can deal with it?

He can't reproduce the error so someone who can should fix it...

**Comment by stepanzharychevbroadcom** [comment] 2020-04-08 10:06
@jellypuno I mean if I can't reproduce it may be you can fix it then, because we have 3 different cases:
1. No bug;
2. Tree warning message (Katelyn);
3. Profile corruption (you);

Of course I can fully uninstall my zowe cli setup and do absolutely everything from scratch to be fully sure. But it will take time.

**Comment by jellypuno** [comment] 2020-04-08 13:43
**Initial Assessment:** The issue happens in [this line (#1762) ](https://github.com/zowe/vscode-extension-for-zowe/blob/master/src/extension.ts#L1762) when node is processed. The end value for node is undefined so when it goes in [this line (#1790)](https://github.com/zowe/vscode-extension-for-zowe/blob/master/src/extension.ts#L1790) it abends with "Cannot read property 'contextValue' of undefined.

**Comment by katelynienaber** [comment] 2020-04-14 06:48
@jellypuno Could you update your comment? Something got merged to master and now I think the line numbers are off...sort of guessing that you meant lines [#1778](https://github.com/zowe/vscode-extension-for-zowe/blob/2cb86b96095a78049170c635ef2f408899ebe161/src/extension.ts#L1778) and [#1833](https://github.com/zowe/vscode-extension-for-zowe/blob/2cb86b96095a78049170c635ef2f408899ebe161/src/extension.ts#L1833)...?

**Comment by Colin-Stone** [comment] 2020-04-14 16:35
Case sensitivity issue. See if it works when you use uppercase for your demo name.  Have a look at this line in extenstion.ts saveFile
![image](https://user-images.githubusercontent.com/30794003/79250026-05fe1600-7e76-11ea-90ff-a018819138f0.png)

**Comment by katelynienaber** [comment] 2020-04-15 06:51
Ya this is what I fixed in PR #680 @Colin-Stone 

(need to make some noise about the weird Jenkins errors...#680 and some others have them...)

**Closed** 2020-04-21 04:39 UTC
Labels: Datasets, bug
