### ISSUE TITLE
EPERM error when running unit tests locally

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#710] opened 2020-04-20 14:01 UTC
When some of us are running unit tests locally, we get an EPERM error caused by the` jest-stare` reporter

![image](https://user-images.githubusercontent.com/58596139/79759473-03406c80-831f-11ea-87ea-459a242d018b.png)

Error occurs in fs functions `mkdirsSync` and `mkDirSync`...
![image](https://user-images.githubusercontent.com/58596139/79759535-16ebd300-831f-11ea-8614-7ddec85685a3.png)
`const dirs` is set to an array: `['C:', 'Users', 'theUser', ...]`
...and then on line 35 `mkDirSync `is called with `C:/` as the argument, somehow passes the test on line 26, and fs tries to make directory `C:/`
...and then we get the EPERM error shown above P:

The error does _not_ occur on the following unit tests: extension, DatasetTree, ZoweJobNode, USSTree

But all subsequent tests have the error.

**Comment by lauren-li** [comment] 2020-04-21 14:22
The errors I get when running unit tests locally look a little different. I'm on a Mac, though, if that makes a difference:
<img width="680" alt="Screen Shot 2020-04-21 at 10 21 22 AM" src="https://user-images.githubusercontent.com/45975633/79877224-fb81d600-83b9-11ea-95af-d152998b8d37.png">

**Comment by CForrest97** [comment] 2020-04-22 13:46
I am also experiencing this issue but have noticed that running `npm t` works fine. So this must be something to do with VSCode's debugger

**Comment by tjohnsonBCM** [comment] 2020-04-22 13:49
The problem went away for me when I modified the arguments passed to Jest in `.vscode/launch.json` to be identical to the arguments used in `npm run test`:
```json
"args": [
    ".*__tests__.*\\.unit\\.test\\.ts",
    "--coverage"
],
```

**Comment by lauren-li** [comment] 2020-04-22 13:55
Thanks @tjohnsonBCM, that got rid of those unit test errors for me as well.

**Comment by CForrest97** [comment] 2020-04-22 14:25
This didnt work for me, Jest reported no tests found and then after 10 seconds I got an error
```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:41490).
```
However, doing `"args": ["${workspaceFolder}/**/*.unit.test.ts"],` worked fine for me

**Comment by tjohnsonBCM** [comment] 2020-04-22 14:32
This is my complete configuration for Jest unit tests in `.vscode/launch.json`:
```json
{
    "type": "node",
    "name": "Unit Tests (Jest)",
    "request": "launch",
    "program": "${workspaceFolder}/node_modules/jest/bin/jest",
    "args": [
        ".*__tests__.*\\.unit\\.test\\.ts",
        "--coverage"
    ],
    "cwd": "${workspaceFolder}",
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen"
}
```
The inclusion of "cwd" should point Jest where to find the tests.

> However, doing `"args": ["${workspaceFolder}/**/*.unit.test.ts"],` worked fine for me

Passing an absolute path should work equally well 😄

**Comment by CForrest97** [comment] 2020-04-22 14:46
Im not sure whats wrong with my system then because even when I use that exact launch configuration it still cant find any matches
This is my full configuration that is working (without absolute path)
```
{
      "type": "node",
      "name": "Unit Tests (Jest)",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      "args": ["__tests__/**/*.unit.test.ts"],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
```

This is the response when I use your config
```
craigforrest@Craigs-MBP vscode-extension-for-zowe %  cd /Users/craigforrest/Documents/zowe/vscode-extension-for-zowe ; /usr/local/bin/node --inspect-brk=48458 node_modules/jest/bin/jest.js .*__tests__.*\\.unit\\.test\\.ts --coverage 
zsh: no matches found: .*__tests__.*\.unit\.test\.ts
```

**Comment by tjohnsonBCM** [comment] 2020-04-22 15:10
@CForrest97 Nothing wrong with your system, my bad 😢 

The `npm run test` script uses a regex pattern to match the tests to run:
`\".*__tests__.*\\.unit\\.test\\.ts\"`

I copied that without realizing that the VSCode launch.json doesn't seem to handle escaping characters very well. So the config I suggested happened to work with Git Bash on Windows, but breaks in some other shells.

I believe the simpler wildcard pattern that you suggested:
`__tests__/**/*.unit.test.ts`
is a better alternative, since it worked for you and also for me when I tried it. Hopefully this will work on all platforms 😄

**Comment by CForrest97** [comment] 2020-04-22 15:27
After doing some more playing around, I noticed that adding the `"__tests__/**/*.unit.test.ts"` isnt what fixes the problem. It is removing `--runInBand` that fixes the `mkdir '/'` issue.
(I dont have theia testing setup so the `"__tests__/**/*.unit.test.ts"` is actually required but the fault lies in using --runInBand)

**Comment by katelynienaber** [comment] 2020-04-29 11:35
For me also removing --runInBand did the trick.

@zFernand0 Would it be possible to remove this argument permanently?

**Comment by zFernand0** [comment] 2020-04-29 14:28
> For me also removing --runInBand did the trick.
> 
> @zFernand0 Would it be possible to remove this argument permanently?

We can remove it for unit tests. However, performing system tests in parallel may cause unexpected problems.
As for the overall jest-stare problem, I believe @tjohnsonBCM and @awharn may have a better sollution. 😋

**Comment by lauren-li** [comment] 2020-04-29 14:41
Removing `--runInBand` also gets rid of these errors for me. However, it also seems like the `--runInBand` argument is needed to be able to use breakpoints when debugging unit tests. Is anyone else finding differently?

**Comment by tjohnsonBCM** [comment] 2020-04-29 17:12
Created #759 which should fix errors when unit tests are run with `--runInBand`. The problem is related to mocks not getting restored correctly. Wrote a more detailed explanation in https://github.com/zowe/vscode-extension-for-zowe/issues/751#issuecomment-621320712.

**Comment by katelynienaber** [comment] 2020-04-30 07:45
Okay great! Yes I hadn't read your description when I posted. Sounds good.

**Comment by zFernand0** [comment] 2020-05-06 18:38
fixed by https://github.com/zowe/vscode-extension-for-zowe/pull/776

**Closed by zFernand0** 2020-05-06 18:38 UTC
