### ISSUE TITLE
Peform a Search for Datasets when a new connection profile is created. 

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#312] opened 2019-11-19 02:59 UTC
Auto Search.  When a user creates a profile, the extension should be able to do a search on the root folder of the entered user name. For a connection, they can optionally enter a user name and password. If they include the user name and password, the extension can search on that user's data-sets. This feature was included in the original z/OS Explorer. It is a nice feature and a time saver for users. This auto search would mean that the system would attempt a connection as soon as the user creates a profile. See the flow diagram named ' 03 Auto-Connecting and Default Search' This feature was referred to as 'My Data Sets’ default filter in the z/OS Explorer extension.

**Comment by MikeBauerCA** [comment] 2019-11-19 12:50
Closing as duplicate of #217

**Closed by MikeBauerCA** 2019-11-19 12:50 UTC
