### ISSUE TITLE
Overwrite File Message - Do you want to overwrite changes made on file system?

### ISSUE THREAD

**Issue by jalel01** [zowe/vscode-extension-for-zowe#317] opened 2019-11-20 15:24 UTC
In a Che Theia environment, the below message appears in Zowe Explorer after it had been left idle for a while. The message also appears after doing a screen refresh.

![Attachment](https://user-images.githubusercontent.com/47416452/69251368-92e7c080-0bb1-11ea-8318-f7db55d3b702.png)

#280 Same message seen here.

**Comment by MarkAckert** [comment] 2019-11-20 15:33
I think this occurs due to usage of user (global) settings. The Zowe Explorer stores profile metadata in user settings, so the number of prompts you see upon refresh increase with the number of connection profiles managed in the Zowe explorer.

Can Zowe explorer profile metadata be stored in workspace (local) settings? Is it configurable? May be a good short-term workaround.

**Comment by MikeBauerCA** [comment] 2019-12-12 14:13
@crawr could you please assign this issue to a target milestone (1.1, 1.2, or 1.3)?

**Comment by crawr** [comment] 2019-12-16 14:28
Changing the configuration from global to local will prevent these pop-up error message.

Open questions and considerations:
- Should this implementation of local config settings just be unique to a Theia route or should this be implemented to VSCode as well?
- For persistence of profiles, can this settings file be tied to the .zowe folder?
- Can the pop-ups be turned off by default and is it possible to be enabled again?

**Comment by Colin-Stone** [comment] 2019-12-16 15:41
>     * Should this implementation of local config settings just be unique to a Theia route or should this be implemented to VSCode as well?
I would say, try it. I don't have any objections for the persisted values for favorites, history and sessions to become local particulalry if it means consistency between Theia and VSCode. I wouldn't want to touch anything else such as Zowe-Temp-Folder-Location as I don't understand it's use.

**Comment by crawr** [comment] 2020-01-09 14:13
**Updates and Findings:**

* Changing the configuration target from Global to Local did not solve this issue. The same pop-up confirmation occurs, just pointing to a local file.
* Changing the call to getConfiguration based on Theia API did not solve the issue.
* Eclipse Theia team confirmed that this is a bug on Theia side and there is a planned fix for it.
* I opened an [issue in Theia repository (#6845)](https://github.com/eclipse-theia/theia/issues/6845) so I can track the fix there. 
* This issue will be moved to Backlog and closed when the Theia issue is resolved.

**Comment by crawr** [comment] 2020-02-25 14:08
Fixed by [PR #7110 in Theia repository](https://github.com/eclipse-theia/theia/pull/7110)

The pop-up does not appear on startup, after session has been left idle for a while, and after screen refresh.

**Closed by crawr** 2020-02-25 14:08 UTC
Labels: Theia
