### ISSUE TITLE
Respect the USS encoding of files in the editor

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-zowe#887] opened 2020-06-17 14:27 UTC
**Is your feature request related to a problem? Please describe.**
On USS files can be encoded, e.g.

![image](https://user-images.githubusercontent.com/28100302/84910051-50865380-b0ae-11ea-996a-cf54b66a288e.png)

ISO8559-1 files are becoming more frequent on USS, especially .json files for Node, as well as Zowe itself that uses this encoding for its application.yml files by the API Mediation Layer.

The problem is the Zowe Explorer always tries to convert the files from EBCDIC, so encoded files open as garbled characters, and also when data is saved it is garbled on save.

The Zowe Explorer allows for manual toggling between file types, however if it could respect the USS encoding this would make it more usable.

This has been reported to me by a number of users as a block for Zowe Explorer adoption, as other z/OS editors and workbenches do respect USS encoding tags.

**Describe the solution you'd like**

Before the file is retrieved look at the tagging, see CLI issue https://github.com/zowe/zowe-cli/issues/740 that describes the z/OSMF API that can be used to retrieve the tagging.

When the file is opened display it in the text codepage and when the file is saved store it using the X-IBM-Data-Type so that data is not garbled on save

**Additional context**

The associated Git CLI issue https://github.com/zowe/zowe-cli/issues/740 covers some of the REST API commands to retrieve the tagging as well as stop the converstion on the data get and put.

**Comment by 1000TurquoisePogs** [comment] 2020-06-22 17:43
One thing you must be careful of is when things are tagged wrongly. Sometimes this happens due to human error, other times it happens because configuration of some software is wrong, leading to automatic incorrect tagging.
So, I'd say you should respect tags but allow overrides, in case the tag is just wrong.
Also, when it comes to tagging, node that while many code pages are numbered the same as they are named (1047 = ibm-1047), iso8859-1 is number 819 I believe, so accepting either a string or a number is good for UX.

**Comment by t1m0thyj** [comment] 2023-02-13 18:12
Currently we implement `isFileTagBinOrAscii` on the ZoweExplorerApi:
https://github.com/zowe/vscode-extension-for-zowe/blob/963e6c79f2ed632c8b998a72acecf2696ed4ae7b/packages/zowe-explorer-api/src/profiles/ZoweExplorerApi.ts#L103-L109

We should consider deprecating this method and replacing it with `applyTaggedEncoding`. This method was added in Zowe CLI v7.6.0 and supports other encodings besides binary and ASCII.
https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/methods/utilities/Utilities.ts#L119-L126

**Comment by AnthonyGiorgio** [comment] 2023-11-14 21:42
This is a problem for me when I want to edit my Python files on z/OS.  They are in ASCII format, and VS Code makes a mess of them.

**Comment by t1m0thyj** [comment] 2023-12-19 19:58
Closing as duplicate of #2435

**Closed by t1m0thyj** 2023-12-19 19:58 UTC
Labels: enhancement, priority-medium
