### ISSUE TITLE
Prompt when adding profile to USS refer to Data Set Explorer

### ISSUE THREAD

**Issue by markcocker** [zowe/vscode-extension-for-zowe#72] opened 2019-05-08 15:42 UTC
Clicking on the + sign to the right of "UNIX SYSTEM SERVICES (USS)" results in the prompt"Select a Profile to Add to the Data Set Explorer".

This should instead refer to UNIX SYSTEM SERVICES (USS).

By comparison clicking on + next to JOBS results in prompt "Select a Profile to Add to the Jobs Explorer".

**Comment by ChrisBoehmCA** [comment] 2019-05-08 15:43
Hi thanks for the issue but this is a duplicate of #56

**Closed** 2019-05-08 16:13 UTC

**Comment by ChrisBoehmCA** [comment] 2019-05-08 16:37
Thanks, fixed in 0.15.1
