### ISSUE TITLE
Copy & Paste PDS member should prefill filename field

### ISSUE THREAD

**Issue by AnthonyGiorgio** [zowe/vscode-extension-for-zowe#1013] opened 2020-09-15 15:52 UTC
**Is your feature request related to a problem? Please describe.**

When performing a copy & paste operation on a PDS member, the dialog for the filename of the pasted member starts out blank.

**Describe the solution you'd like**

The dialog should be prefilled with the filename of the copied member, and all the text selected.  This way pressing Enter will perform the copy with the existing filename, and pressing any other key will overwrite the selection text to use a different name.

**Describe alternatives you've considered**

**Additional context**

**Comment by mpettis** [comment] 2020-11-13 15:18
A strong second to this enhancement request.

**Comment by mpettis** [comment] 2020-11-13 15:21
Duplicate of request in https://github.com/zowe/vscode-extension-for-zowe/issues/874

**Comment by jelaplan** [comment] 2020-11-16 20:26
@mpettis This is similar but I don't think it is even necessary to prompt the user at all. Just copy it with the same name unless copying to the same data set. That said, I think the suggestion to auto-fill the prompt is a lot better than what we have.

**Closed** 2021-02-24 18:31 UTC
Labels: 21PI1, Sprint 1, enhancement
