### ISSUE TITLE
Deleting multiple files or datasets is tedious

### ISSUE THREAD

**Issue by esubah1989** [zowe/vscode-extension-for-zowe#258] opened 2019-10-04 14:10 UTC
When deleting multiple files from USS or deleting multiple datasets, you have to delete each file or datasets separately.  I think it would be nice to have multiple files or datasets selection capability. On Mac for example, you can select multiple items for deletion by holding command key and click the items that you want to delete.

**Comment by t-o-m-e-k** [comment] 2019-10-04 15:25
I would like to ask for a similar functionality but for "toggle binary" action.
Some products have number of configuration files in ASCII and a possibility to switch all needed files at once would be nice.

This requests is similar to #224

**Comment by Colin-Stone** [comment] 2019-10-08 07:47
Closing this issue as a duplicate of #224 
Thomasz your suggestion could be a new issue/enhancement.

**Closed by Colin-Stone** 2019-10-08 07:47 UTC
Labels: duplicate
