### ISSUE TITLE
GetJobs using Tokens

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1050] opened 2020-10-22 13:23 UTC
**Describe the bug**

I submitted a job using a profile with token. After clicking the jobID, I encountered this error:

![image](https://user-images.githubusercontent.com/45042840/96877882-80899d00-147a-11eb-95a9-36f080972f5c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS:
-   Zowe Explorer Version:
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by katelynienaber** [comment] 2020-12-08 14:52
@jellypuno I think this is a duplicate of issue [#1088](https://github.com/zowe/vscode-extension-for-zowe/issues/1088) and therefore should be linked to PR [#1097](https://github.com/zowe/vscode-extension-for-zowe/pull/1097)...

**Comment by jellypuno** [comment] 2020-12-08 14:56
@katelynienaber Yes I think so too. Thank you

**Closed** 2020-12-10 09:39 UTC
Labels: bug, duplicate
