### ISSUE TITLE
Not able to delete job with Zowe RSE profile

### ISSUE THREAD

**Issue by oakmount66** [zowe/vscode-extension-for-zowe#996] opened 2020-08-31 07:43 UTC
From within VScode I can use my Zowe RSE profile to list Host Datasets, USS datasets and Host jobs. But when I try to delete a job I get an Invalid Credentials message.

![image](https://user-images.githubusercontent.com/60236192/91694287-afffe580-eb6c-11ea-93fe-9f533765d192.png)

When I use my z/OSMF profile a delete works fine.

![image](https://user-images.githubusercontent.com/60236192/91694455-d9207600-eb6c-11ea-888c-642c1832a54e.png)

I do not use SCS and it's the same user/password for the two profiles.

Zowe CLI version: 6.19.1
VScode version: 1.48.2
z/OS version: v2.4

**Comment by oakmount66** [comment] 2020-08-31 08:19
Just found this in the host log

![image](https://user-images.githubusercontent.com/60236192/91698690-6a92e680-eb73-11ea-882a-c7c604a15cf6.png)

**Comment by lauren-li** [comment] 2020-09-02 19:38
@oakmount66 Thank you for reporting this issue. I have created a copy of the issue in the IBM Z Open Editor repository, as the issue is only occurring with your RSE profile: https://github.com/IBM/zopeneditor-about/issues/77

Please use the above link to track work and additional discussion for this issue. I will go ahead and close the issue in this repository since it pertains to more to IBM Z Open Editor.

**Closed by lauren-li** 2020-09-02 19:38 UTC
Labels: bug
