### ISSUE TITLE
ZOWE Explorer 2.0.0 stops working when opening a workspace in Windows mounted using z/OS NFS

### ISSUE THREAD

**Issue by cybersorcerer** [zowe/vscode-extension-for-zowe#1773] opened 2022-04-29 05:50 UTC
Hi,

i upgraded ZOWE Explorer, ZOWE CLI and IBM Z Open Editor to the new Versions (ZOWE Explorer 2.0.0, ZOWE CLI 7.0.2, IBM Z Open Editor 2.0.2). When i open a VS Code Workspace on my local hard drive, everything works fine. As you can see from the following screen shot, ZOWE Explorer is open in the sidebar and an assembler source file (coming from a workspace from my local harddrive) is in VS Code and IBM Z Open Editor is doing it's job (as you can see from the entries in the menu).

![image](https://user-images.githubusercontent.com/33680802/165884662-90bce038-8c47-4075-9cf9-d7f8449703d4.png)

But my usual workflow is different. The git repositories are located inside z/Unix, i mount the required directories using the Windows NFS Client  to my desktop PC. I use make together with some simple VS Code tasks definitions (zowe cli zos-ssh) for CI/CD.  When i open a VS Code Workspave or Folder from the NFS share the following happens:

1. A windows pops up with the following error message: "Error encountered while activating and initializing logger! Error: EBUSY: resource busy or locked, realpath 'y:\hlasm\RUVZS-ApplicationManagementInfrastructure'" The path is the NFS Share
2. ZOWE Explorer looses all profiles
3. IBM Z Open Editor stops working 

Have a look at the screenshot below. The ZOWE Explorer view on the left side is empty (i.e no profiles). The popup in the editor does not have the Goto Definitions, Goto References anymore. In addition (not on the screen shot). The outline is empty which is another indication that IBM Z Open Editor did stop working as well. I assume this is because ZOWE hast lost its profiles.

![image](https://user-images.githubusercontent.com/33680802/165887862-5f66b98d-747c-4237-9f82-c1b928daecbb.png)

This all worked without any problems for at least 2 years with the previous version of zowe cli, zowe explorer and IBM Z Open Editor. In order to fix this and get ZOWE Explorer to work again i have to do the following:

1. Close the folder
2. Open a folder from the local hard drive
3. Restart VS Code

1. Mount a z/Unix directory using the Windows NFS Client, here is the mount command i am using:
    `mount -o mtype=hard \\mvst.ruv.de\hfw\u\xv880aj\Documents\source,text y:`
4. Open a Folder located on the share
5. Open a source code file from the folder or workspace just opened
6. Go back to the ZOWE Explorer Icon
7. The Profiles should be gone. 

Sometimes the error message does not pop up. In this case you need to exit out of VS Code without closing the editor and restart it to see the error message.

- OS: MS Windows 10 Build 19044.1645
- Zowe Explorer Version: 2.0.0
- (Optional) Zowe CLI Version: 7.0.2
- IBM Z Open Editor 2.0.2
- VS Code Version: 1.66.2

I checked the zowe.log. The last message in the log is:

> [2022/04/29 06:59:12.698] [ERROR] [extension.js:32] Error encountered while activating and initializing logger! {"errno":-4082,"syscall":"realpath","code":"EBUSY","path":"y:\\hlasm\\RUVZS-ApplicationManagementInfrastructure"}
<

Nothing after this line anymore until i fix the problem. This could be a timing related problem with NFS Shares. The device is not busy as indicated in the error message i can edit the file and save it to the share without any issues.

ZOWE Explorer 2.0.0 has to work with NFS mounted shares without any problems as it did before.

regards

Ronny

**Comment by cybersorcerer** [comment] 2022-05-06 16:54
Hi, 
some additional info for you. When i do work on files on my NFS Share and try to save them, i get the following error:
`Command 'zopeneditor.hlasm.truncate' not found`  and the file is not saved to the NFS Share. 

![image](https://user-images.githubusercontent.com/33680802/167176285-0583ee83-54fe-42de-9fb6-c57eef85bc0a.png)

When i then select the ZOWE EXPLORER Icon at the sidebar and try to save again, the error message goes away and the file is saved to the NFS Share.

![image](https://user-images.githubusercontent.com/33680802/167176553-7b5ffac9-7589-470a-860c-00346bb2af48.png)

The next change and save will fail again with the same error and so on.

regards
Ronny

**Comment by rudyflores** [comment] 2022-05-11 19:35
@cybersorcerer if possible can we see the output upon running the `showattr` command against the z/OS server you used when this issue ocurred for you?

example: `showattr -e myhost`

**Comment by cybersorcerer** [comment] 2022-05-12 04:34
@rudyflores  i tried but unfortunately our version of the windows showattr command does not have the -e option.
`PS C:\Users\XV880AJ> showattr -e mvst
GFSA950E Unknown option 'e'.
GFSA972I usage: C:\Users\XV880AJ\zosnfs\showattr.exe [-t?] [--norpcbind] HOST [MOUNTPOINT] [--usage] [--version]`
We are on z/OS 2.4, here is the output of showattr --version
`showattr --version
GFSA961I showattr (z/OS NFS utilities) 2.4, Aug  7 2019 16:35:05
Licensed Materials - Property of IBM
"Restricted Materials of IBM"
5650-ZOS
Copyright IBM Corp. 1991, 2019 All Rights Reserved.
US Government Users Restricted Rights - Use,
duplication or disclosure restricted by
GSA ADP Schedule Contract with IBM Corp.
Copyright SUN Microsystems, Inc &
Electronic Data Systems Corp. 1988, 1989`

regards
Ronny

**Comment by cybersorcerer** [comment] 2022-06-01 14:00
Hello,

any news on this?

Thx in advance

Ronny

**Comment by zFernand0** [comment] 2022-06-10 11:11
hey @cybersorcerer,
Thanks for your patience.
I'm getting setup to replicate an environment similar to yours.
I'll reach out as soon as I have some good news 😋

**Comment by zFernand0** [comment] 2022-06-13 14:35
Hey @cybersorcerer,
Tested on Win 10 (19044.1708) with a NFS share created on WSL2.
I'm still able to use the Zowe Explorer extension with profiles loaded from the zowe.config.json file
I'm no expert with NFS Shares, but I couldn't reproduce the EBUSY error even when the file was technically in use on the host
![image](https://user-images.githubusercontent.com/37381190/173377998-dbd6f9c5-579a-4af6-b4c3-f0cb48fff7e9.png)

**Comment by cybersorcerer** [comment] 2022-06-13 15:02
Hey @zFernand0,

NFS inside WSL is for sure not the same as a z/OS NFS Server. You should recreate the Environment using a z/OS NFS Server,the Windows NFS Client with the extensions to the Windows mount command as described in my first post. I hope you do have access to a z/OS System.

Regards

Ronny

**Comment by cybersorcerer** [comment] 2022-07-22 04:26
Hi,

Are there any news?

Regards 
Ronny

**Comment by zFernand0** [comment] 2022-08-11 14:58
Hey @cybersorcerer 
It would be beneficial if we could have a chat on Slack 😋 
https://join.slack.com/t/openmainframeproject/shared_invite/zt-1e1p0elcm-F0s4L9CSSr3eGNke3pBtrQ

**Comment by cybersorcerer** [comment] 2022-08-29 04:07
@zFernand0 i joined and i am on slack now

**Comment by cybersorcerer** [comment] 2022-11-20 13:48
Hi,

Any news? 

Regards Ronny

**Comment by cybersorcerer** [comment] 2022-12-03 12:35
Hi Guys,

Still no news? Thats a bit underwhelming

Greetings

Ronny

**Comment by zFernand0** [comment] 2022-12-03 22:41
Hey @cybersorcerer,
My apologies for not delivering timely responses.
I will ask for help from other team members as I alone cannot seem to get to the bottom of this issue.
Thank you for being patient.
I will reply here as soon as I am able to progress further.
Again, sorry for the delay on this. :cry:

**Comment by cybersorcerer** [comment] 2023-03-29 06:24
Hi guys,

I had hopes that somehow this really annoying bug would go away with bew releases. Unfortunately it did not go away but something changed after the installation of ZOWE Explorer 2.7.0. It stll diesebt wirk abd the symptoms i have described are stll the same but with 2.7.0 i now see an error message popup. Look at the following screenshot: 

![image](https://user-images.githubusercontent.com/33680802/228444041-c3232e60-9535-4262-acf5-b45fa757ec2a.jpeg)

When i click on the Show Config button, no config us shown i.e the click doesn't do anything and as described before all targets are gone. I really hope soneone starts working on this

Regards 
Ronny

**Comment by zFernand0** [comment] 2023-03-29 12:56
hey @cybersorcerer,
Could you share the following files?
- any `zowe.config.json` available
- any `zowe.schema.json` available
- the `<path-to>/.zowe/settings/imperative.json` (where `<path-to>` is `~`, `$home`, or `$ZOWE_CLI_HOME`)

**Comment by cybersorcerer** [comment] 2023-03-30 04:19
Ok, here is the doc you requested. There is only one zowe.config.json and zowe.schema.json which i have attached. There is NO imperative.json, neither in $HOME nor in $ZOWE_CLI_HOME. I do not know why you are requesting those files. The files you requested seem completely unrelateted to the error i reported! Why don't you ask for logs or the like? The popup only occurs when i work on z/OS NFS Shares! When i open projects on my local windows harddrive and go the the ZOWE Explorer everything works, no popup, no errors! All i have reported so far is related to projects opend on windows drives mapped to a z/OS NFS SHARE!
I suggest you read thru the whole thing again to make sure you understand the problem! I am getting a bit angry, this took far to long and it looks to me i keep getting "keep the customer busy" questions! Maybe you should talk to project members a bit more experianced with z/OS and z/Unix.

[doc.zip](https://github.com/zowe/vscode-extension-for-zowe/files/11107646/doc.zip)

**Comment by zFernand0** [comment] 2023-03-30 12:12
Hey @cybersorcerer,
I can imagine how frustrating this must be for you. 
Personally, I would be frustrated as well if the community support I received was not helping to get towards a resolution.
And for that I want to apologize.

> Why don't you ask for logs or the like?

I was hesitant that the logs would not have been very helpful given the unique environment and that we (Zowe Explorer) may not be surfacing most errors appropriately and no debug messages were being captured (until this [Pull Request](https://github.com/zowe/vscode-extension-for-zowe/pull/2006) that is)

> There is NO imperative.json, neither in $HOME nor in $ZOWE_CLI_HOME. I do not know why you are requesting those files. The files you requested seem completely unrelateted to the error i reported!

Thanks for sharing.
The reason for me asking about these files is because the Zowe Explorer extension needs to be able to write/touch all three at different stages of the initialization process. (see details in [ProfileUtils](https://github.com/zowe/vscode-extension-for-zowe/blob/main/packages/zowe-explorer/src/utils/ProfilesUtils.ts#LL378C33-L378C33))
And seeing the message you shared regarding Zowe Explorer having troubles loading your Zowe config, ([introduced recently](https://github.com/zowe/vscode-extension-for-zowe/pull/2056) as well) tells me that this is likely a client-side issue (not related to z/OS components).

Based on your explanation, and without seeing the logs, I believe this is related to the Zowe Explorer not being able to write the `imperative.json` file.
![image](https://user-images.githubusercontent.com/37381190/228830675-9d459650-8f19-4a96-a9e2-e7c26e895fd8.png)

Steps forward:
1. Please make sure the ZFS (specially the `.zowe` directory) is mounted with read-write permissions 
2. Zowe Explorer should surface the error properly about not being able to write the `.zowe/settings/imperative.json` file.

> I suggest you read thru the whole thing again to make sure you understand the problem! I am getting a bit angry, this took far to long and it looks to me i keep getting "keep the customer busy" questions! Maybe you should talk to project members a bit more experianced with z/OS and z/Unix.

At this point, I will unassing myself and communicate in the Zowe Explorer Standop (open-call in the zowe-calendar) that a more z/OS experienced member is desired.

Regards,
Fernando.

**Comment by cybersorcerer** [comment] 2023-03-31 04:43
Hi @zFernand0,

This is of course a client side issue. As i described at the very beginning of this issue, it did work for a long time with Zowe Explorer 1.x and it stopped working with the first install of Zowe Explorer 2. Nothing had changed on the z/OS side of the story. I am using VSCode on Windows! The .zowe directory is in my $HOME and of course it is read and writable by my userid! There is NO .zowe directory on the z/OS NFS share! The share (z/Unix file system) does contain git repos cloned with git in z/OS. By mounting the z/Unix folders with the Windows nfs Client, the VSCode built in git client works with git repos in z/Unix which is a big advantage. Zowe Explorer 2 seems to do unneccesary stuff when a VSCode Workspace mounted with the Windows nfs client is opened. As i said it looses all z/OSMF Profile definitions. This causes IBM Z Open Editor to stop working, so there is no syntax highlighting and other lsp related stuff anymore. This all worjed beautifully with Zowe Explorer 1

Regards
Ronny

**Comment by traeok** [comment] 2023-04-06 18:02
Hi @cybersorcerer ,

I've made some adjustments to how we build project/workspace directories for Windows systems. Seeing the context of this error message, I am hopeful that this fix will resolve your issue. I was wondering if you could verify this by testing a `.vsix` (VS Code extension) file that contains the fix? I will attach it to this comment.

To install an extension from a VSIX:

1. Click on the "Extensions" panel on the left-hand side
2. Click on the "meatball" or "kebab" menu (three dots) at the top of the Extensions view:
![image](https://user-images.githubusercontent.com/86500639/230427621-63967f44-a9fc-4b75-8b24-acec218f079d.png)
3. Click "Install from VSIX..."
4. Select the downloaded VSIX in the file browser that appears, and click "Install"
5. Once finished, VS Code will prompt you to reload the window to apply the extension changes.

If the error still occurs after installing the new VSIX, the extension logs will help clarify the source of the problem. In this case, please attach the extension logs to this thread and we will continue to diagnose the source of this issue.

To access the extension logs:
1. Press Ctrl+Shift+P, or click "View" -> "Command Palette" to open the Command Palette
2. Search or look for the option: "Developer: Open Extension Logs Folder"
3. Select this option, and a file explorer will appear containing the extension logs.
4. Please upload the `exthost.log` file that appears in this folder.

Thanks again for your feedback and patience regarding this issue.

---

[Zowe Explorer VSIX (realpath fix).zip](https://github.com/zowe/vscode-extension-for-zowe/files/11173312/Zowe.Explorer.VSIX.realpath.fix.zip)

**Comment by cybersorcerer** [comment] 2023-04-07 19:11
Hi @traeok,

I am currently on vacation. I will be back in the office on tuesday. I will test an report the results.

Greetings
Ronny

**Comment by cybersorcerer** [comment] 2023-04-11 04:49
Good Morning @traeok,

I just installed the version you provided and it definitely fixed the issue! 

Greetings

Ronny

**Comment by traeok** [comment] 2023-04-11 13:34
Hi @cybersorcerer ,

Excellent, glad to hear! We merged in the fix today - it will be included with the next minor release of Zowe Explorer, v2.8.0.
Feel free to reply to this thread if you have any more questions or concerns regarding this issue.

Closing as completed in #2224.

Thanks,
Trae

**Closed by traeok** 2023-04-11 13:34 UTC
Labels: bug, priority-medium, severity-high
