### ISSUE TITLE
no zftp profile type option after installed Zowe Explorer Extension for FTP version 1.16.0

### ISSUE THREAD

**Issue by tiantn** [zowe/vscode-extension-for-zowe#1377] opened 2021-06-28 02:13 UTC
I found there is no option to create zftp profile when I upgraded to v1.16.0.
![图片](https://user-images.githubusercontent.com/23715327/123569658-55213400-d7f9-11eb-8449-5db1b8271989.png)
The old version has the option of profile type but the new version doesn’t have this, I can only create z/OSMF profile.

**Comment by Joe-Winchester** [comment] 2021-06-28 14:44
Thank you @tiantn for opening this.  @AndrewTwydell and I came across this actually working with a Zowe Explorer customer which surprised us as prior to 1.16.0 it had worked well for us.  Good news is that the customer was already using Zowe FTP extension !  We'll share it with them when a fix becomes available and if you'd like us to do some early testing please let us know.

**Comment by lauren-li** [comment] 2021-06-28 21:39
This issue is a bit strange, as the Zowe Explorer FTP extension 1.16.0 works well from VS Code's debugger, as well as when installed from the VSIX file generated by a local build. However, inspection of the extension installed from VS Code Marketplace reveals that, unlike the builds described earlier, it is missing the `out` folder that contains `extension.js` (needed for the extension to run).

I have been working with @zFernand0 on PR #1379 to address a possible cause of this, but it is still in the investigation/testing phase, since it doesn't seem that these build/configuration files have actually changed since the Zowe Explorer FTP extension Marketplace installation last worked (other than version number updates).

**Comment by lauren-li** [comment] 2021-06-29 20:48
Zowe Explorer FTP extension 1.16.1 has been released to address this issue, and appears to be working with zftp profiles (create and use). Inspection of the extension installed from VS Code Marketplace shows that the `out` folder containing `extension.js` is now present.

@tiantn @Joe-Winchester @AndrewTwydell Please let us know in this issue if the problem is not resolved in Zowe Explorer FTP extension 1.16.1. Thank you!

**Comment by tiantn** [comment] 2021-06-30 01:49
Hi @lauren-li, the 1.16.1 version resolved the problem. Now it works well. Thank you very much!

**Comment by lauren-li** [comment] 2021-06-30 12:24
> Hi @lauren-li, the 1.16.1 version resolved the problem. Now it works well. Thank you very much!

@tiantn Great to hear! Thank you for testing out 1.16.1 and confirming the issue is resolved there. 🎉

**Closed** 2021-06-30 13:28 UTC
Labels: bug
