### ISSUE TITLE
Data loss when saving a member

### ISSUE THREAD

**Issue by seroyer** [zowe/vscode-extension-for-zowe#1046] opened 2020-10-19 14:29 UTC
**Describe the bug**

The contents of one member were erroneously replaced by a different member when saving.

**To Reproduce**

I was using zowe explorer version 1.9 for vscode to develop hlasm modules for a class.  I had a split view with two source members (`findname` and `convexp` from the same data set) open on the left and some members from other data sets on the right (output).  I edited `findname` and hit save.  The focus switched to `convexp` and the contents of `findname` were saved into `convexp`.  The contents of `findname` were the same as before editing it and `convexp` had all of `findname` including all of the changes I had made.  All of the contents of `convexp` were lost.

**Expected behavior**

Don't lose data.

**Screenshots**

![Screenshot 2020-10-19 092836](https://user-images.githubusercontent.com/16136912/96464515-8585ec80-11ed-11eb-82c6-d15e8bbdf09e.png)

**Desktop (please complete the following information):**

-   OS: Windows 10 2004
-   Zowe Explorer Version: 1.9
-   (Optional) Zowe CLI Version: 6.23.0
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by jellypuno** [comment] 2021-01-15 14:41
@seroyer With the recent v1.11.1 is this error still happening?

**Comment by katelynienaber** [comment] 2021-01-20 10:38
@jellypuno I managed to reproduce this on the current master branch...but it is intermittent. Trying to find the cause...

**Comment by jellypuno** [comment] 2021-01-20 10:44
@katelynienaber thank you for testing. I am also manually testing the current master branch.

**Comment by katelynienaber** [comment] 2021-01-20 10:46
@jellypuno maybe not related, but I just got a weirdd error, where if you change files while it's saving, the one you are saving ends up with the contents of BOTH files...

**Comment by crawr** [comment] 2021-03-02 16:00
Closing issue. Feedback needed

**Closed by crawr** 2021-03-02 16:00 UTC
Labels: 21PI1, Priority: High, bug
