### ISSUE TITLE
Refresh zowe explorer with profile changes

### ISSUE THREAD

**Issue by dboudreaux** [zowe/vscode-extension-for-zowe#499] opened 2020-02-06 08:54 UTC
When I update my zowe profile (say with a new password) using the CLI, zowe explorer does not recognize the change, and is seeming to use some sort of cached ID & PW. If you click on the refresh icon, the old profile information is still used. Note: Listing Dataset on the CLI uses the correct profile info. 

If I close down VS Code and restart it, Zowe Explorer recognizes the changed profile, but this is not what I expect.

**Comment by jalel01** [comment] 2020-02-06 11:51
There is some overlap here with the need to be able to edit profiles in Zowe Explorer #319

**Comment by Colin-Stone** [comment] 2020-02-06 12:24
Duplicate of https://github.com/zowe/vscode-extension-for-zowe/issues/161

**Comment by MikeBauerCA** [comment] 2020-02-07 08:28
Closing as duplicate but this is a significant issue that needs to be resolved.

**Closed by MikeBauerCA** 2020-02-07 08:28 UTC
