### ISSUE TITLE
PERFORM VARYTING

### ISSUE THREAD

**Issue by ROBIN-Olivier** [zowe/vscode-extension-for-zowe#1972] opened 2022-10-14 14:03 UTC
Hello,
The Cobol Snippet "PERFORM VARYING" is labeled PERFORM VARYTING (with a T between the Y and the I).
Could you correct it?
Thanks

on a new line of a cobol program, type "PERFORM VARY"

**Screenshots**
![VSCode-varyting](https://user-images.githubusercontent.com/103997342/195865244-3a5ba726-7df6-4a3c-bffe-bd8a880ac838.png)

OS: Windows
Zowe Explorer Version: v2.3.0

**Comment by zFernand0** [comment] 2022-10-14 15:56
Hey Robin, thanks for opening the issue.
This seems related to the COBOL Language Support
https://github.com/eclipse/che-che4z-lsp-for-cobol
I 'm afraid I'm not able to transfer the issue though.

Please open the issue in the lsp-for-cobol repository.
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/new/choose
Closing for now! 😋

**Closed by zFernand0** 2022-10-14 15:56 UTC
Labels: bug

**Comment by zimlu02** [comment] 2022-10-17 14:47
Hi @ROBIN-Olivier,
what COBOL LS version has been used, please? I cannot reproduce it on the latest 1.0.2 version.
Thank you
