### ISSUE TITLE
Support File Diff Comparisins from in ZE

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#876] opened 2020-06-12 21:42 UTC
**Problem**
VS Code supports diff comparisons from within the VS Code Explorer panel. And users of Zowe can download data sets or files and then user that other panel to do this. But, this is super non-obvious. Doing diff comparisons is a foundational feature of editors and IDEs. Supporting this feature is one that will make ZE a professional tool rather than a toy as someone once described it. 

**Solution**
Add the VS Code diff capabilities into the ZE extension. 

This image shows the native VS Code diff comparison feature. What we are asking for is to include these options in the ZE context menus. 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/3207260/84548632-0f6bf900-acd4-11ea-81d7-e2a992595840.png">

**Comment by FALLAI-Denis** [comment] 2020-06-20 17:39
Something usefull would be « compare with host ». 
Under ISPF/PDF this is « COMPARE * » command.

**Comment by venkatzhub** [comment] 2020-06-24 23:15
@jelaplan - describing the use cases that would detail what the source and target for comparison would be very helpful. I can think of:
selecting two PDS members and doing a compare, 
selecting a local file (e.g a Git artifact) and a PDS member and doing compare (this might the compare with host @FALLAI-Denis  is referring to)

**Comment by Joe-Winchester** [comment] 2022-04-22 12:06
@zFernand0 and @JillieBeanSim ,  this looks like a duplicate of https://github.com/zowe/vscode-extension-for-zowe/issues/1533 (that has one upvote) and also https://github.com/zowe/vscode-extension-for-zowe/issues/246 (that has five upvotes).  
I have a customer who has also asked for this feature and I wanted to point them at an issue to upvote, but want to not have the upvotes lost/diluted.   Wondering if there is a way we can consolidate the three compare issues into a single one ?    Maybe keep https://github.com/zowe/vscode-extension-for-zowe/issues/246  that has the most number of upvotes and close the other two ?

**Comment by zFernand0** [comment] 2022-04-22 13:16
I like your idea of keeping #246.
Combined, all 3 issues have a total of 6-7 different people interested (either they opened it, 👍 or 🚀 other issues)

**Comment by zFernand0** [comment] 2022-04-22 13:16
Closing in favor of #246

**Closed by zFernand0** 2022-04-22 13:16 UTC
Labels: enhancement
