### ISSUE TITLE
Separate console window

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1556] opened 2021-10-25 18:52 UTC
Separate console window for each instead of same title for both Zowe Command

**Comment by roman-kupriyanov** [comment] 2022-02-01 18:07
@JillieBeanSim yes, the case confirmed. There is an OUTPUT tab with different channel names for TSO/MVS:

![image](https://user-images.githubusercontent.com/91762867/152025218-327272c3-62b4-4eb8-87dc-9001fdb74f50.png)

Seems that it was fixed some time ago by Katelyn in this PR: https://github.com/zowe/vscode-extension-for-zowe/pull/1478

**Comment by JillieBeanSim** [comment] 2022-02-01 18:10
closing issue since this was completed with PR https://github.com/zowe/vscode-extension-for-zowe/pull/1478

**Closed by JillieBeanSim** 2022-02-01 18:10 UTC
Labels: enhancement, 21PI4, Command(TSO/MVS)
