### ISSUE TITLE
Favorite search/filter cause duplicate profiles

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1810] opened 2022-05-16 14:10 UTC
**Describe the bug**

Running dataset search multiple times always adds a new node to the tree
ℹ️ This also applies to USS and Jobs 
ℹ️ Also happens in Theia

**To Reproduce**
 
1. Save a dataset search/filter
2. Click on the search
3. Change the filter on the added session
4. Repeat from step 2 ♾️ 

**Expected behavior**

Identify that the profile was already added, and perform the search against it

**Screenshots**

![image](https://user-images.githubusercontent.com/37381190/168610874-4e1755df-4d34-4efd-adfa-b93e8e9e9701.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version: 7.2.0
- (Optional) Are you using Secure Credential Store? No

**Additional context**

Found this while trying to reproduce #1809, where no parent node may exist for a given node
Also, it throws these errors:
![image](https://user-images.githubusercontent.com/37381190/168610994-cbc5d539-92a9-4d27-8b74-98a9f0bee064.png)

**Comment by JillieBeanSim** [comment] 2022-06-21 18:49
@zFernand0 is this a duplicate of https://github.com/zowe/vscode-extension-for-zowe/issues/1029 just in a different view?

**Closed** 2022-06-21 18:53 UTC
Labels: bug
