### ISSUE TITLE
zftp: Members aren't saved, message "Saving data set..." but nothing happens and never ends.

### ISSUE THREAD

**Issue by ssamayoa** [zowe/vscode-extension-for-zowe#2499] opened 2023-10-06 18:47 UTC
**Describe the bug**

zftp
Members aren't saved, message "Saving data set..." but nothing happens and never ends.
Some time works but most of the time doesn't. 
Used to work all the time but suddenly this erratic behavior began.

**To Reproduce**

1. Create new PDS
2. Create new member
3. Write something then save.
4. message "Saving data set..." but nothing happens and never ends.

**Expected behavior**
Members saved.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 22H2 10.0.19045.3448
- Zowe Explorer Version:  2.11.0
- Are you using Secure Credential Store? not sure.

**Additional context**

-  At start-up I get, since the beginning this message:

Error: Unable to initialize secure credentials plugin for Z Open Editor. Check that you configured the "Zowe Security: Credential Key" user preferences with the value "Zowe-Plugin". Error returned: "Failed to initialize secure credential manager"

- When "Zowe Explorer" shows  the data set list, I can see 2 tasks in SDSF:

OLS0009  STEP1             STC06059 OLS0009  
OLS0009  DBPROCBG TCP00027 TSU06101 OLS0009  
OLS0009  STEP1             STC06093 OLS0009  

DBPROCBG is my TN3270 session.

- I'm the administrator of the mainframe and haven't changed any configuration.
- Saved members (when works) does not have Size, Created, Changed or ID - should them?
- Where and/or how I can see what's happening?
- From CLI (zowe zos-ftp upload...) works fine.

**Comment by ssamayoa** [comment] 2023-10-07 16:17
**UPDATE:**

I configured TRACE level to "Zowe Explorer"'s log, connected to another z/OS and found that after the ds is saved this are the output:

[2023/10/07 10:10:54] [TRACE] dataset.utils.getProfileAndDataSetName called.
[2023/10/07 10:10:54] [TRACE] ZoweDatasetNode.getEtag called.
[2023/10/07 10:10:56] [TRACE] ZoweDatasetNode.setEtag called.

But connected to our main z/OS last line never show and the message "Saving data set..." stays for ever.

FWIW both z/OS are 2.4

What else I should check?

**Comment by JillieBeanSim** [comment] 2024-01-09 16:07
the startup error is from the secure credentials being used, which is default for Zowe.  This could cause other issues while trying to use the Zowe Profiles.

`Error: Unable to initialize secure credentials plugin for Z Open Editor. Check that you configured the "Zowe Security: Credential Key" user preferences with the value "Zowe-Plugin". Error returned: "Failed to initialize secure credential manager"`

@ssamayoa is this a Windows Virtual Machine?  Also, Is this still happening with latest versions?

**Comment by ssamayoa** [comment] 2024-01-09 16:13
Hi @JillieBeanSim 

> @ssamayoa is this a Windows Virtual Machine? Also, Is this still happening with latest versions?

No, is not VM, and yes, still happens, seldom and randomly for datasets containing COBOL and ASM source but almost all the time with datasets containing JCL.

**Comment by JillieBeanSim** [comment] 2024-01-09 17:32
Thanks @ssamayoa are you still experiencing the error message about credentials on startup? 
Can you also share ZE version, VS Code version, and are you using v1 profiles stored in a .yaml file within ~/.zowe directory or a Team configuration file (.json) to handle profiles?

**Comment by ssamayoa** [comment] 2024-01-09 18:22
> are you still experiencing the error message about credentials on startup? 

Nope, I haven't had connection issues.

> Can you also share ZE & ZE for zFTP version, VS Code version, and 

zOE: v3.3.3
zFTP extension: v2.13.1
VSC: 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

> are you using v1 profiles stored in a .yaml file within ~/.zowe directory or a Team configuration file (.json) to handle profiles?

Team configuration file (.json)

**Comment by SanthoshiBoyina** [comment] 2024-01-10 05:21
Hello @ssamayoa ,
As per the initial comment, the mentioned OS was Windows 10. As per the latest comment, the OS Windows_NT x64 10.0.22631 is Windows 11. 

Would you confirm if the OS where you encountered the issue is Windows 10 or Windows 11?

**Comment by ssamayoa** [comment] 2024-01-10 15:57
> Would you confirm if the OS where you encountered the issue is Windows 10 or Windows 11?

I just get a new laptop that's why is Windows 11 now.
Note that I had the same problem with the plugin in Ubuntu 22.04.

**Comment by JTonda** [comment] 2024-02-01 16:10
#2533

**Comment by JillieBeanSim** [comment] 2024-02-14 16:28
Fixed with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2712 and published with 2.14.1.
@ssamayoa can you verify the fix please?

**Comment by ssamayoa** [comment] 2024-02-14 16:51
> Fixed with PR #2712 and published with 2.14.1. @ssamayoa can you verify this is fixed please?

In a smoke test it works.
Thanks!

**Closed** 2024-02-14 16:57 UTC
Labels: bug, Research Needed, priority-high, severity-high
