### ISSUE TITLE
Members aren't saved, message "Saving data set..." but nothing happens and never ends.

### ISSUE THREAD

**Issue by ssamayoa** [zowe/vscode-extension-for-zowe#2533] opened 2023-10-06 18:28 UTC
**Describe the bug**
Members aren't saved, message "Saving data set..." but nothing happens and never ends.
Some works but most of the time doesn't. 
Used to work and suddenly stopped.

**Expected and actual results**

1. Expected behavior:
Members saved.

2. Actual behavior:
Members aren't saved

3. Applicable log files:
Where I can see the log file for the pluing?
I only get this line from "IBM Z Open Editor":

2023-10-06T12:03:03.552-06:00 DEBUG: Saving the current JCL document with a maximum line length value of 80 ("zopeneditor.jcl.maximumLineLength" setting).

**Describe your environment**
- NodeJS: v18.13.0
- NPM: 9.4.1
- Operating system and version: Windows 10 22H2 10.0.19045.3448
- Shell/terminal: "IBM Z Open Editor" / "Zowe Explorer"

**Additional context**
-  At start-up I get, since the beginning this message:

Error: Unable to initialize secure credentials plugin for Z Open Editor. Check that you configured the "Zowe Security: Credential Key" user preferences with the value "Zowe-Plugin". Error returned: "Failed to initialize secure credential manager"

- When "Zowe Explorer" shows  the data set list, I can see 2 tasks in SDSF:

OLS0009  STEP1             STC06059 OLS0009  
OLS0009  DBPROCBG TCP00027 TSU06101 OLS0009  
OLS0009  STEP1             STC06093 OLS0009  

DBPROCBG is my TN3270 session.

- I'm the administrator of the mainframe and haven't changed any configuration.
- Saved members (when works) does not have Size, Created, Changed or ID - should them?
- Where and/or how I can see what's happening?

**Comment by ssamayoa** [comment] 2023-10-06 18:40
FWIW I tried from command line and worked so is very likely that the problem is in "IBM Z Open Editor".

**Comment by std4lqi** [comment] 2023-10-09 06:27
@ssamayoa Will look into it soon. Thanks!

**Comment by std4lqi** [comment] 2023-10-10 06:25
Hi @ssamayoa , some questions we have to understand the problem better.

* Did the problem happen when you saved PDS member with IBM Z Open Editor?
* Did the problem happen when you saved PDS member with Zowe Explorer 2.11.0?
* When you edit an existing member, can you save it successfully?
* You can upload PDS member with Zowe CLI via FTP, right?
* Did the problem happen only on your main z/OS system? It didn't happen on your another z/OS system, right?
* If you got the different result on two z/OS systems, could you provide the PDS attributes like LREC shown in ISPF, on both two z/OS systems?

Thanks!

**Comment by std4lqi** [comment] 2023-10-10 07:15
Sometimes, the following dialog in Zowe Explorer asks for choice, but doesn't show on the front due to some reason, while you just see `Saving data set ...` on the status bar. You can click `Saving data set ...` to bring the dialog on the font.

![image](https://github.com/zowe/zowe-cli-ftp-plugin/assets/31643673/bb9078c4-bf74-49d8-9c0f-9b9fa959201a)

**Comment by ssamayoa** [comment] 2023-10-10 14:54
> Hi @ssamayoa , some questions we have to understand the problem better.
> 
> * Did the problem happen when you saved PDS member with IBM Z Open Editor?
YES

> * Did the problem happen when you saved PDS member with Zowe Explorer 2.11.0?
YES

> * When you edit an existing member, can you save it successfully?
NO

> * You can upload PDS member with Zowe CLI via FTP, right?
YES

> * Did the problem happen only on your main z/OS system? It didn't happen on your another z/OS system, right?
Yes, that's the weirdest thing: It fails on IBM's Dallas ISV Center but works fine in zPDT instance. 
I compared FTP configuration and are almost identical.
Note that in IBM's Dallas ISV machine sometimes works but most not and haven't find the exact flow when it works.

> * If you got the different result on two z/OS systems, could you provide the PDS attributes like LREC shown in ISPF, on both two z/OS systems?

Is the same: 80 on both systems.
I'm editing COBOL & JCL datasets.

Dallas:
Data class . . . . . : **None**
 Organization  . . . : PO      
 Record format . . . : FB      
 Record length . . . : 80      
 Block size  . . . . : 27920   
 1st extent megabytes: 2       
 Secondary megabytes : 2       
 Data set name type  : LIBRARY 
 Data set encryption : NO      
 Data set version  . : 1       

zPDT:

General Data                 
 Volume serial . . . : A4SYS1
 Device type . . . . : 3390  
 Organization  . . . : PO    
 Record format . . . : FB    
 Record length . . . : 80    
 Block size  . . . . : 6160  
 1st extent tracks . : 1     
 Secondary tracks  . : 1     
 Data set encryption : NO    

(ignore that I created in SYS vol :p )
However I can note that in Dallas is LIBRARY and has bigger block size while in zPDT is "classic" PDS.
Might be the cause?
Some obscure information of FTP in z/OS I should know?

Thanks!

**Comment by ssamayoa** [comment] 2023-10-10 15:16
> Sometimes, the following dialog in Zowe Explorer asks for choice, but doesn't show on the front due to some reason, while you just see `Saving data set ...` on the status bar. You can click `Saving data set ...` to bring the dialog on the font.
> 
> ![image](https://user-images.githubusercontent.com/31643673/273808292-bb9078c4-bf74-49d8-9c0f-9b9fa959201a.png)

I noticed that in https://github.com/zowe/vscode-extension-for-zowe/blob/main/packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts but I haven't seen that message neither the one you said covers it when the save fails.

**Comment by std4lqi** [comment] 2023-10-12 06:43
Thanks, @ssamayoa ! PDS member (LIBRARY with block size of 27920 ) saving from Zowe Explorer worked well at our side.

You can save SEQ dataset from Zowe Explorer, right?

**Comment by ssamayoa** [comment] 2023-10-14 02:06
> PDS member (LIBRARY with block size of 27920 ) saving from Zowe Explorer worked well at our side.

I noticed that zowe explorer was updated from 2.11 to 2.11.1 to I give a try.
Save feels slow but seems working now - haven't used extensively yet.
May be a larger timeout somewhere?
I will back to work with VS Code instead of TSO/ISPF and let you know if I have some problem then.
 
> You can save SEQ dataset from Zowe Explorer, right?

I haven't tried, I started to use VS Code/zowe recently focused on coding - I will try next week and let you know the result.

**Comment by ssamayoa** [comment] 2023-10-15 17:55
**UPATE**
Still randomly failing.
I weird that most of the time with small and medium COBOL program does not fail but with short JCL does - but still don't found what exactly conditions make it fail.
Just in case I created a new PDSE with smaller block size and copied the JCLs there but save still fails.
This is driving me crazy!

**Comment by std4lqi** [comment] 2023-10-17 06:16
Do you have any problem in saving SEQ dataset? I suppose you mean "Saving data set ..." never ended by `fail`.

I suspect it might be relevant to the text longer than LREC. Could you remove the trailing space characters over the LREC, and then save it? Here are how I remove the trailing spaces over LREC.

1. Set up ruler in VS Code. Go to `Settings`, and input `ruler`. Then click `Edit in settings.json` in the following screen.
<img width="1228" alt="image" src="https://github.com/zowe/zowe-cli-ftp-plugin/assets/31643673/b3b803d8-ae31-4440-b6c8-ec01739c1940">

2. Add LREC like 80 into editor rulers. Then you will get the vertical line at column 80 in editor.
```
    "editor.rulers": [
        80
    ],
```

3. Show whitespace characters by selecting `Render Whitespace` in the following screen. The whitespace will be rendered as `.`.
![image](https://github.com/zowe/zowe-cli-ftp-plugin/assets/31643673/49bb9141-ed88-45ef-95c2-9c494e6d97f1)

4. Ensure no character or whitespace over the ruler, before saving data set.

**Comment by ssamayoa** [comment] 2023-10-17 12:41
@std4lqi thank you for your effort but I'm pretty sure is not the record length.
FWIW I have a ruler line at column 80 and render white spaces enabled.

Additional note:
When the save get stuck, if I try to edit the member in ISPF it complains "member in use" - seems that one of the parties (FTP server or plugin) is missing some signal like "EOF", "I'm ready", etc.

Again, this is driving me crazy!

**Comment by traeok** [comment] 2023-11-03 14:42
Hi @ssamayoa,

Does your LPAR support multiple active FTP connections under a single user? I've adjusted how we handle FTP connections in the Data Sets and USS operations (#2526), so if your LPAR only allows one active connection per user, this fix may address your issue. This particular fix will be released with 2.12.1.

**Comment by traeok** [comment] 2023-11-29 18:40
Hi @ssamayoa,

I just wanted to follow up and verify whether v2.12.1 resolved your issues with FTP and saving data sets.
Feel free to reply in this thread if you are still encountering the issue.

(Also, adding #2499 in this comment to link the two related issues)

**Comment by ssamayoa** [comment] 2023-12-05 07:05
@traeok Thank you for following this issue.
I'm still experience save hangs :(
I haven't found what are the step to reproduce however I think is something in our mainframe because I recently downloaded several members (600+) from a dataset using Filezilla and after +/-200 failed but then restarting the queue remaining 400+ were downloaded without a problem.
As soon as I have time I will dig into policy agent configuration, maybe there is something there that is causing this odd behaviour.

**Comment by JillieBeanSim** [comment] 2024-01-29 22:38
I am able to recreate this issue on Windows 10 uploading a save changes to MVS data set member that is JCL

**Comment by ssamayoa** [comment] 2024-01-29 23:26
> I am able to recreate this issue with zftp profile on Windows 10 uploading a save changes to MVS data set member that is JCL

So I'm not crazy and is not my mainframe fault! :p

**Comment by JillieBeanSim** [comment] 2024-01-30 12:25
Updated the priority & severity to HIGH since this recreation caused loss of data, the file on host was empty after the save attempt

**Comment by traeok** [comment] 2024-01-30 15:40
> I am able to recreate this issue with zftp profile on Windows 10 uploading a save changes to MVS data set member that is JCL

This might not help much, but I wanted to add some additional info:

I tested this again with my `zftp` profile, and it doesn't seem to happen as long as the lines are within the 80-character line length for JCL files.
 
However, I did notice strange behavior with the "Saving data set" status message when I get a truncation dialog such as [the scenario above](https://github.com/zowe/vscode-extension-for-zowe/issues/2533#issuecomment-1785458027). The status message persists and the file is empty on the host as @JillieBeanSim mentioned.

**Comment by std4lqi** [comment] 2024-01-31 04:19
Hi @JillieBeanSim , did you reproduce it with the line less than 80-character?

**Comment by tiantn** [comment] 2024-01-31 07:57
Hi @JillieBeanSim , we can recreate the problem when edit a member start with `//` in the first line on windows. We are investigating it now. Thank you!

**Comment by std4lqi** [comment] 2024-02-01 13:28
Hi @JillieBeanSim , @traeok , we believe this issue happens when the file to upload contains `//` at the first line. 

When uploading text to FTP server, FTP client checks whether the string to put is a local file path first, using `fs.stat()`. If yes, it puts the whole file to the server; otherwise, it puts the string as the contents to the server. 

On windows, error is thrown when FTP client uses fs.stat() with the file path starting with "//". You can open "Help -> Toggle Developer Tools" from VS Code. When you upload the file containing like
```
// abc
```

you can find the error message like

```
UNC host '// ...'  access is not allowed
```

The fix PR is created at https://github.com/zowe/zowe-cli-ftp-plugin/pull/152

Thanks to @tiantn and all people here for your testing so many times to catch it!

**Comment by zFernand0** [comment] 2024-02-12 20:16
The CLI PR was merged and published.
Thanks @tiantn and @std4lqi for fixing the issue.
Now we just need a quick PR to update the plug-in in the FTP extension.
I don't mind opening one in a few minutes.

**Closed** 2024-02-13 14:56 UTC
Labels: bug, priority-high, zFTP, severity-high
